# version: '3.7'
services:
  # Node Version 22.5.1 enviroment
  reactdev251:
    container_name: react_dev_251
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.reactdev251
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./public
          action: sync
          target: /west/github/velocity_knight_trainer_webapp
          ignore:
            - node_modules/
        # - action: rebuild
        #   path: package.json
    restart: always
    volumes:
      - .:/west/github/velocity_knight_trainer_webapp:delegated
    # - .ssh/:/root/.ssh:rw 
    # hostname: 'reactdev251'
    environment:
      - CHOKIDAR_USEPOLLING=true
networks:
  default:
    name: node_dev
    external: true


